<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJJpvV7s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJJpvV7s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJJpvV7s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJJpvV7s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJJpvV7s\App_KernelDevDebugContainer([
    'container.build_hash' => 'JJpvV7s',
    'container.build_id' => '08c8b410',
    'container.build_time' => 1663820001,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJJpvV7s');
