version: '3'
services:
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'datum'
            MYSQL_USER: 'datum'
            MYSQL_PASSWORD: 'datum123'
            MYSQL_ROOT_PASSWORD: 'datum123'
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - '4306:3306'
    php:
        container_name: php
        build:
            context: ./php
        ports:
            - '9000:9000'
        volumes:
            - ./app:/var/www/symfony_docker
        depends_on:
            - database
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./app:/var/www/symfony_docker
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
