<?php

namespace ContainerJJpvV7s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NcJC85BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ncJC85B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ncJC85B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'anonymousApiLimiter' => ['privates', 'limiter.anonymous_api', 'getLimiter_AnonymousApiService', true],
        ], [
            'anonymousApiLimiter' => '?',
        ]);
    }
}
