<?php

namespace ContainerJJpvV7s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateHashesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateHashesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateHashesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('avato:test', [0 => 'avato:test'], 'creates new hashes', false, #[\Closure(name: 'App\\Command\\CreateHashesCommand')] function () use ($container): \App\Command\CreateHashesCommand {
            return ($container->privates['App\\Command\\CreateHashesCommand'] ?? $container->load('getCreateHashesCommandService'));
        });
    }
}
