<?php

namespace ContainerJJpvV7s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateHashesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateHashesCommand' shared autowired service.
     *
     * @return \App\Command\CreateHashesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateHashesCommand.php';

        $container->privates['App\\Command\\CreateHashesCommand'] = $instance = new \App\Command\CreateHashesCommand(($container->privates['App\\Service\\HashService'] ?? $container->load('getHashServiceService')));

        $instance->setName('avato:test');
        $instance->setAliases([0 => 'avato:test']);
        $instance->setDescription('creates new hashes');

        return $instance;
    }
}
